preset: recommended
risky: true
enabled:
  - concat_with_spaces
disabled:
  - concat_without_spaces
  - blank_line_before_return
  - no_blank_lines_after_class_opening
finder:
  name: "*.php"
  not-name: "*.blade.php"