preset: recommended
risky: true
enabled:
  - concat_with_spaces
  - single_blank_line_at_eof
disabled:
  - concat_without_spaces
  - blank_line_before_return
finder:
  name: "*.php"
  not-name: "*.blade.php"